namespace: ahmadalli
name: ansible
version: 0.0.1
readme: README.md
authors:
  - Ahmadali Shafiee (https://ahmadalli.rocks) <mail@ahmadalli.net>
license:
  - "MIT"
tags:
  - collection
  - containers
  - podman
  - docker
  - opennebula
repository: https://github.com/ahmadalli/ansible
