---
- name: set comman facts
  ansible.builtin.include_vars: common.yaml
- name: copy keys
  synchronize:
    src: /var/lib/mysql/{{ item }}
    dest: /var/lib/mysql/{{ item }}
  delegate_to: "{{ groups[percona_xtradb_cluster_inventory_group_name][0] }}"
  loop:
    - ca-key.pem
    - ca.pem
    - server-key.pem
    - server-cert.pem
- name: write mysqld configuration files
  template:
    src: mysqld-{{ percona_xtradb_cluster_version }}.conf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
    owner: root
    group: root
    mode: "0644"
- name: write wsrep configuration files
  template:
    src: wsrep-{{ percona_xtradb_cluster_version }}.conf.j2
    dest: /etc/mysql/mysql.conf.d/wsrep.cnf
    owner: root
    group: root
    mode: "0644"
