- name: remove config directories
  ansible.builtin.file:
    path: /etc/firewalld/{{ item }}
    state: absent
  loop:
    - icmptypes
    - ipsets
    - services
    - zones
- name: create config directories
  ansible.builtin.file:
    path: /etc/firewalld/{{ item }}
    owner: root
    group: root
    mode: "0755"
    state: directory
  loop:
    - icmptypes
    - ipsets
    - services
    - zones
- name: remove direct configs
  file:
    state: absent
    path: /etc/firewalld/direct.xml
  ignore_errors: yes
- name: reload firewalld
  command: /usr/bin/firewall-cmd --complete-reload
  register: _firewalld_reload_result
  failed_when: _firewalld_reload_result.rc != 0
  changed_when: _firewalld_reload_result.rc == 0
