- name: clear configs
  ansible.builtin.file:
    path: /etc/firewalld/{{ item[0] }}
    owner: root
    group: root
    mode: "0755"
    state: "{{ item[1] }}"
  with_nested:
    - - icmptypes
      - ipsets
      - services
      - zones
  loop:
    - absent
    - directory
- name: remove direct configs
  file:
    state: absent
    path: /etc/firewalld/direct.xml
  ignore_errors: yes
- name: reload firewalld
  command: firewall-cmd --complete-reload
  register: _firewalld_reload_result
  failed_when: _firewalld_reload_result.rc > 0
  changed_when: _firewalld_reload_result == 0
