- name: set zone identification facts
  set_fact:
    _config_key: "{{ 'zone_' + _zone_name if (_zone_name | default('', true) | length > 0) else 'default_zone' }}"
    _is_default_zone: "{{ _zone_name | default('', true) | length == 0 }}"

- name: set zone configuration facts
  set_fact:
    _interfaces: "{{ lookup('vars', 'firewalld_' + _config_key + '_interfaces', default=[]) | unique }}"
    _sources: "{{ lookup('vars', 'firewalld_' + _config_key + '_sources', default=[]) | unique }}"
    _source_hosts: "{{ lookup('vars', 'firewalld_' + _config_key + '_source_hosts', default=[]) | unique }}"
    _ports: "{{ lookup('vars', 'firewalld_' + _config_key + '_ports', default=[]) | unique }}"
    _services: "{{ lookup('vars', 'firewalld_' + _config_key + '_services', default=[]) | unique }}"
    _rich_rules: "{{ lookup('vars', 'firewalld_' + _config_key + '_rich_rules', default=[]) | unique }}"

- name: add _source_hosts to sources
  set_fact:
    _sources: "{{
      _sources |
      union(
        query('inventory_hostnames', (_source_hosts | default([inventory_hostname], true))) |
        map('extract', hostvars) |
        map(attribute='ansible_host') |
        difference([ansible_host])
      ) |
      unique }}"
- name: remove non-ip values from sources
  set_fact:
    _sources: "{{ _sources | ansible.netcommon.ipaddr }}"
- name: make all sources subnet
  set_fact:
    _sources: "{{ _sources | map('ansible.netcommon.ipsubnet') }}"
- name: generate redundant sources list
  set_fact:
    _redundant_sources: "{{ _redundant_sources | default([], true) | union(_sources | ansible.netcommon.ipaddr(item) | difference([item])) | unique }}"
  loop: "{{ _sources }}"
- name: remove redundant sources
  set_fact:
    _sources: "{{ _sources | difference(_redundant_sources) }}"
- name: create zone
  when: not _is_default_zone
  block:
    - name: ensure zone is present
      ansible.posix.firewalld:
        zone: "{{ _zone_name | mandatory }}"
        state: present
        permanent: yes
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded

- name: add interfaces
  ansible.posix.firewalld:
    zone: "{{ _zone_name | default(omit, true) }}"
    interface: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ _interfaces }}"

- name: add sources
  ansible.posix.firewalld:
    zone: "{{ _zone_name | default(omit, true) }}"
    source: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ _sources }}"

- name: add ports
  ansible.posix.firewalld:
    zone: "{{ _zone_name | default(omit, true) }}"
    port: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ _ports }}"

- name: add services
  ansible.posix.firewalld:
    zone: "{{ _zone_name | default(omit, true) }}"
    service: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ _services }}"

- name: add rich rules
  ansible.posix.firewalld:
    zone: "{{ _zone_name | default(omit, true) }}"
    rich_rule: "{{ item }}"
    state: enabled
    permanent: yes
    immediate: yes
  loop: "{{ _rich_rules }}"

- name: setup firewalld_zone_public_masquerade
  ansible.posix.firewalld:
    zone: "{{ _zone_name | default(omit, true) }}"
    masquerade: yes
    state: enabled
    permanent: yes
    immediate: yes
  when: firewalld_zone_public_masquerade | default(false, true)
