---
- name: remove old configs
  file:
    path: /etc/netplan
    state: absent
- name: recreate netplan directory
  file:
    path: /etc/netplan
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: generate netplan config file
  copy:
    dest: /etc/netplan/config.yaml
    content: |
      # Ansible managed
      {{ network_links | ahmadalli.ansible.to_netplan | to_yaml }}
    owner: root
    group: root
    mode: "0644"
- name: test netplan configs
  command: netplan generate
  register: netplan_generate
  failed_when: netplan_generate.rc > 0
  changed_when: netplan_generate == 0
- name: apply configs
  command: netplan apply
  register: netplan_apply
  failed_when: netplan_apply.rc > 0
  changed_when: netplan_apply == 0
