- name: set configuration fact
  set_fact:
    key_value: dummy # just to make the error go away
    __docker_daemon_configs:
      registry-mirrors: "{{ docker_daemon_configs_registry_mirrors | default([], true) }}"
      insecure-registries: "{{ docker_daemon_configs_insecure_registries | default([], true) }}"
      ip: "{{ docker_daemon_configs_ip | default('0.0.0.0', true) }}"
      iptables: "{{ docker_daemon_configs_iptables | default('true') | bool }}"
      dns: "{{ docker_daemon_configs_dns | default([], true) }}"
      log-driver: "{{ docker_daemon_configs_log_driver | default('json-file') }}"
      log-opts: "{{ docker_daemon_configs_log_opts | default({}, true) }}"
      features:
        buildkit: "{{ docker_daemon_configs_features_buildkit | default(false, true) | bool }}"
  tags:
    - facts
- name: create docker configs directory
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: "0755"
- name: docker configs
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ __docker_daemon_configs | to_json }}"
    owner: root
    group: root
    mode: "0644"
  notify: restart docker
- name: systemd configs
  when: docker_systemd_unit_env | default([], true) | length > 0
  block:
    - name: remote other overrides
      when: docker_systemd_unit_manage_overrides | default(false, true)
      block:
        - name: list current overrides
          find:
            paths: "{{ docker_systemd_unit_overrides_directory }}"
            patterns: "*.conf"
            file_type: file
          register: _docker_override_files
        - name: remove other overrides
          file:
            path: "{{ item }}"
            state: absent
          loop: '{{ _docker_override_files.files | map(attribute="path") | difference([docker_systemd_unit_overrides_file]) }}'
    - name: make sure systemd directory is created
      file:
        path: "{{ docker_systemd_unit_overrides_directory }}"
        state: directory
        owner: root
        group: root
        mode: "0644"
    - name: docker systemd env
      template:
        src: systemd.conf.j2
        dest: "{{ docker_systemd_unit_overrides_file }}"
        owner: root
        group: root
        mode: "0644"
      notify: restart docker
    - name: add ansible-managed file to directory
      when: docker_systemd_unit_manage_overrides
      copy:
        dest: "{{ docker_systemd_unit_overrides_directory }}/ansible-managed"
        content: |
          this directory is managed by ahmadalli.ansible.docker-configure role
        owner: root
        group: root
        mode: "0644"
- name: login in registries
  when: docker_registry_authentications | default([], true) | length > 0
  block:
    - name: make sure docker pip is present
      vars:
        pip_install_packages:
          - name: docker[tls]
      include_role:
        name: geerlingguy.pip
    - name: login in registry
      include_tasks: login.yaml
      loop: "{{ docker_registry_authentications }}"
