- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}.yaml"
    - "{{ ansible_os_family|lower }}.yaml"
    - default.yaml
  tags:
    - facts
- name: install gluster client package
  ansible.builtin.include_role:
    name: utils/os/package/manager
- name: update /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED BLOCK gluster mount role"
    block: |
      {% for glusterMount in glusterfs_mounts %}
      {%   for host in query('inventory_hostnames', glusterfs_mounts.hosts) %}
      {{ hostvars[host]['ip'] | default(hostvars[host]['ansible_host'] ,True) }} {{ host }}
      {%   endfor %}
      {% endfor %}
- name: create mount directory if necessary
  include: mountpoint.yaml
  loop: "{{ glusterfs_mounts }}"
- name: mount the mountpoint
  mount:
    name: "{{ item.mount.path }}"
    src: "{{ query('inventory_hostnames', item.hosts) | random }}:/{{ item.volume }}"
    fstype: glusterfs
    opts: "defaults,_netdev,noauto,x-systemd.automount"
    state: mounted
  loop: "{{ glusterfs_mounts }}"
