- name: get mount path stats
  ansible.builtin.stat:
    path: "{{ item.mount.path }}"
  register: p
- name: check if recreating path is possible
  ansible.builtin.fail:
    msg: |
      the mount path {{ item.mount.path }} exists but it's not a directory. and path_force_create is not set to true
  when: p.stat.exists and not p.stat.isdir and not path_force_create
- name: remove the contents of the path
  ansible.builtin.file:
    state: absent
    path: "{{ item.mount.path }}"
  when: p.stat.exists and not p.stat.isdir
- name: ensure the mount directory is created
  ansible.builtin.file:
    state: directory
    path: "{{ item.mount.path }}"
    mode: "{{ '%04d' | format(item.mount.mode | default(755, true) | int) }}"
    owner: "{{ item.mount.owner | default('root', true) }}"
    group: "{{ item.mount.group | default('root', true) }}"
