- name: ensure repository public key is installed
  action: "{{ _package_repo_key_info.ansible_module }}"
  args:
    id: "{{ item.id | default(omit) }}"
    url: "{{ item.url }}"
    state: present
  loop: "{{ _package_repo_key_info.repo_keys | default([], true) }}"

- name: ensure repository is enabled
  action: "{{ _package_repo_info.ansible_module }}"
  args:
    repo: "{{ item }}"
    state: present
  loop: "{{ _package_repo_info.repos | default([], true) }}"

- name: ensure packages are installed
  action: "{{ _package_info.ansible_module }}"
  args:
    pkg: "{{ item.name }}"
    force: "{{ item.force | default(omit) }}"
    conf_file: "{{ item.yum_conf | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    update_cache: "{{ omit if ansible_distribution == 'Fedora' else True }}"
    enablerepo: "{{ item.repo | default(omit) }}"
    deb: "{{ item.deb | default(omit) }}"
  loop: "{{ _package_info.packages | default([], true) }}"
