- name: install docker-compose
  get_url:
    dest: /usr/local/bin/docker-compose
    url: https://github.com/docker/compose/releases/{{ docker_compose_version | default('latest', true) }}/download/docker-compose-{{ansible_system}}-{{ansible_userspace_architecture}}
    mode: 755
  register: _binary_download_result
  until: "'OK' in _binary_download_result.msg or 'file already exists' in _binary_download_result.msg"
  retries: 4
  delay: 5
- name: setup docker-compose bash completion
  get_url:
    dest: /etc/bash_completion.d/docker-compose
    url: https://raw.githubusercontent.com/docker/compose/master/contrib/completion/bash/docker-compose
    mode: 755
  register: _completion_download_result
  until: "'OK' in _completion_download_result.msg or 'file already exists' in _completion_download_result.msg"
  retries: 4
  delay: 5
