- name: gather os specific variables for dependencies packages
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - dependencies/{{ ansible_distribution | lower }}.yaml
    - dependencies/{{ ansible_os_family | lower }}.yaml
    - dependencies/default.yaml
- name: install dependencies
  ansible.builtin.include_role:
    name: utils/os/package/manager
- name: gather os specific variables for dependencies packages
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - mysql/{{ ansible_distribution | lower }}.yaml
    - mysql/{{ ansible_os_family | lower }}.yaml
    - mysql/default.yaml
- name: install packages
  ansible.builtin.include_role:
    name: utils/os/package/manager
