opennebula_frontend_oned_configs_database_backend: mysql

opennebula_frontend_oned_configs_database_mysql_server: "{{ '127.0.0.1' if mysql_bind_address == '0.0.0.0' else mysql_bind_address }}"
opennebula_frontend_oned_configs_database_mysql_port: "{{ mysql_port | int }}"
opennebula_frontend_oned_configs_database_mysql_user: "{{ mysql_users[0].name }}"
opennebula_frontend_oned_configs_database_mysql_passwd: "{{ mysql_users[0].password }}"
opennebula_frontend_oned_configs_database_mysql_db_name: "{{ mysql_databases[0].name }}"
opennebula_frontend_oned_configs_database_mysql_connections: "{{ (mysql_max_connections | int - 1) | string }}"
opennebula_frontend_oned_configs_database_mysql_compare_binary: "no"

# this can be no, yes, only. For yes and only, provide path to
# cert and key. "yes" means both ws and wss connections will be
# supported.
opennebula_sunstone_server_configs_vnc_proxy_support_wss: "no"
opennebula_sunstone_server_configs_vnc_proxy_cert:
opennebula_sunstone_server_configs_vnc_proxy_key:

opennebula_one_vmm_exec_kvm_config_nic_model: virtio
opennebula_one_vmm_exec_kvm_config_nic_filter:
