---
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}.yaml"
    - "{{ ansible_os_family|lower }}.yaml"
    - default.yaml
  tags:
    - facts

- name: install opennebula frontend packages
  ansible.builtin.include_role:
    name: utils/os/package/manager
