---
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - default.yaml
  tags:
    - facts

- name: install opennebula frontend packages
  include_role:
    name: utils/os/package-manager
