---
- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - defaults.yaml
    - "{{ ansible_os_family|lower }}.yaml"
    - "{{ ansible_distribution|lower }}.yaml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yaml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yaml"
  tags:
    - facts
  ignore_errors: yes

- name: install opennebula frontend packages
  include_role:
    name: ahmadalli.ansible.utils/os/package-manager
