- name: gather os specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}.yaml"
    - "{{ ansible_os_family|lower }}.yaml"
    - default.yaml
  tags:
    - facts
- name: install keepalived
  ansible.builtin.include_role:
    name: utils/os/package/manager

- name: configure vrrp_scripts
  include_tasks: vrrp_script.yaml
  loop: "{{ query('ahmadalli.ansible.listmerge', 'keepalived_vrrp_scripts') }}"
  loop_control:
    loop_var: _vrrp_script

- name: configure keepalived
  template:
    dest: /etc/keepalived/keepalived.conf
    src: keepalived.conf.j2
    mode: "0644"
  notify: restart keepalived
