- name: set facts
  set_fact:
    _php_directory: "{{ _php_directory_stat.path }}"
    _php_version: "{{ _php_directory_stat.path | replace('/etc/php/', '') }}"
- name: list php flavors
  ansible.builtin.find:
    paths: "{{ _php_directory }}"
    file_type: directory
    excludes: 'mods-available'
    recurse: false
  register: _php_flavors
- name: remove newrelic.ini from php flavor
  ansible.builtin.file:
    path: "{{ item.path }}/conf.d/newrelic.ini"
    state: absent
  loop: "{{ _php_flavors.files }}"
- name: create newrelic.ini from template
  ansible.builtin.template:
    src: newrelic.ini.j2
    dest: "{{ _php_directory }}/mods-available/newrelic.ini"
  notify: restart php-fpm
- name: create symlink from newrelic.ini for each flavor
  ansible.builtin.file:
    src: "{{ _php_directory }}/mods-available/newrelic.ini"
    dest: "{{ item.path }}/conf.d/newrelic.ini"
    state: link
  loop: "{{ _php_flavors.files }}"
