- name: set configuration fact
  set_fact:
    key_value: dummy # just to make the error go away
    __docker_daemon_configs:
      registry-mirrors: "{{ docker_daemon_configs_registry_mirrors | default([], True) }}"
      insecure-registries: "{{ docker_daemon_configs_insecure_registries | default([], True) }}"
      ip: "{{ docker_daemon_configs_ip | default('0.0.0.0', True) }}"
      iptables: "{{ docker_daemon_configs_iptables | default('true') | bool }}"
      dns: "{{ docker_daemon_configs_dns | default([], True) }}"
      log-driver: "{{ docker_daemon_configs_log_driver | default('json-file') }}"
      log-opts: "{{ docker_daemon_configs_log_opts | default({}, True) }}"
- name: create docker configs directory
  file:
    path: /etc/docker
    state: directory
    mode: "0755"
- name: docker configs
  copy:
    dest: /etc/docker/daemon.json
    content: "{{ __docker_daemon_configs | to_json }}"
  notify: restart docker
- name: systemd configs
  when: docker_systemd_unit_env | default([], True) | length > 0
  block:
    - name: delete old overrides
      when: docker_systemd_unit_manage_overrides
      file:
        path: "{{ docker_systemd_unit_overrides_directory }}"
        state: absent
    - name: make sure systemd directory is created
      file:
        path: "{{ docker_systemd_unit_overrides_directory }}"
        state: directory
    - name: docker systemd env
      template:
        src: systemd.conf.j2
        dest: "{{ docker_systemd_unit_overrides_file }}"
        mode: "0644"
      notify: restart docker
