firewall_allow_bridge_forward: false
firewall_frontend: firewalld
firewall_frontend_reset: false

# Firewalld Configurations

# https://firewalld.org/documentation/man-pages/firewalld.service.html
# each firewalld_services_<name> represents one firewalld service
# firewalld_services_dummy:
#   name:
#   short_name:
#   description:
#   ports: []
#     # - port:
#     #   protocol:
#   protocols: []
#   source_ports: []
#     # - port:
#     #   protocol:
#   destination:
#     ipv4:
#     ipv6:

# https://firewalld.org/documentation/man-pages/firewalld.direct.html
# note: if a rich rule can be used, then they should always be preferred over direct rules
# also check the Caveats section on the documentation
firewalld_direct_chains: []
  # - ipv: # ipv4|ipv6|eb
  #   table:
  #   chain:
firewalld_direct_rules: []
  # - ipv: # ipv4|ipv6|eb
  #   table:
  #   chain:
  #   priority:
  #   args:
firewalld_direct_passthroughs: []
  # - ipv: # ipv4|ipv6|eb
  #   args:


# default zone configs
# each of these following list configs could be extended by adding a suffix to them.
# so that you can have multiple configurations in different groups and each host
# will have all of them
firewalld_default_zone_interfaces: []
firewalld_default_zone_sources: []
# list of inventory hosts/groups to be added to the zone
firewalld_default_zone_source_hosts: []
firewalld_default_zone_ports: []
firewalld_default_zone_services: []
firewalld_default_zone_rich_rules: []
firewalld_default_zone_masquerade: false
# should be one of these: default, ACCEPT, DROP, REJECT
firewalld_default_zone_target:

# zone configurations
# replace 'public' with any zone you want.
# the zone would be created if it's not already present
# firewalld_zone_<name>_setup should be true for zone setup.
firewalld_zone_public_setup: false
firewalld_zone_public_interfaces: []
firewalld_zone_public_sources: []
# list of inventory hosts/groups to be added to the zone
firewalld_zone_public_source_hosts: []
firewalld_zone_public_ports: []
firewalld_zone_public_services: []
firewalld_zone_public_rich_rules: []
firewalld_zone_public_masquerade: false
# should be one of these: default, ACCEPT, DROP, REJECT
firewalld_zone_public_target:
