name: publish collection
on:
  create:
    tags:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get the version from the tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: artis3n/ansible_galaxy_collection@v2.3.0
        with:
          api_key: '${{ secrets.GALAXY_API_KEY }}'
          galaxy_version: '${{ steps.get_version.outputs.VERSION }}'
