name: test collection
on:
  push:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint collection
        uses: ansible/ansible-lint-action@main
        with:
          override-deps: |
            ansible>=2.10
